apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::149536480497:user/github-ci
      username: github-ci
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::149536480497:role/github-actions-ecr-push
      username: github-actions
      groups:
        - system:masters
